# there is no reason to use this makefile manually

.PHONY: build clean

ifeq (,$(PLATFORM))
$(error please specify PLATFORM, eg. make PLATFORM=tg5040)
endif

.EXPORT_ALL_VARIABLES:
# pseudo toolchain
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CROSS_COMPILE=/usr/bin/
	PREFIX=/usr
endif
ifeq ($(UNAME_S),Darwin)
	# brew installs gcc to e.g. /opt/homebrew/bin/gcc-16, but none of our makefiles
	# support the suffix. Run scripts/desktop/setup-macos-toolchain.sh first to shim
	# a suffix-less gcc into /var/tmp/nxredux/bin (no sudo, no /usr/local/bin writes).
	#       From brew we need at least: brew install sdl2_image sdl2_ttf gcc make libsamplerate sqlite
	CROSS_COMPILE=/var/tmp/nxredux/bin/
	PREFIX=/opt/homebrew
endif
PREFIX_LOCAL=/var/tmp/nxredux
UNION_PLATFORM=desktop

all: 
	
clean:
	cd workspace && make clean
	
build: 
	COMPILE_CORES=$(COMPILE_CORES) cd workspace && make

build-cores: 
    COMPILE_CORES=$(COMPILE_CORES) cd workspace && make cores

build-core:
ifndef CORE
	$(error CORE is not set)
endif
	COMPILE_CORES=$(COMPILE_CORES) CORE=$(CORE) cd workspace && make core
