#ifndef ARCADE_NAMES_H
#define ARCADE_NAMES_H

// Arcade display-name tables: .system/res/arcade/<TAG>.txt, generated by
// scripts/gen-arcade-names.sh from the FBNeo DATs (FBN) and Flycast's Naomi
// tables (DC). Each line is "<zip stem>\t<title>"; BIOS sets carry the title
// "." so hide() drops them, like a "."-prefixed map.txt alias. Titles are
// plain (no revision/region brackets, first of " / " names). The launcher
// consults a table only when map.txt has no alias for the ROM.
//
// Depends on libc only, so the host unit tests can link it directly.

typedef struct ArcadeNames ArcadeNames;

// NULL when the file is missing, unreadable or has no entries.
ArcadeNames* ArcadeNames_load(const char* path);
void ArcadeNames_free(ArcadeNames* self);

// Title for a ROM filename (e.g. "mslug.zip"), or NULL when the table does
// not know it. Only .zip and .7z files are looked up (any case), so disc
// images sharing a folder with arcade sets (DC's .chd/.gdi) keep their names.
const char* ArcadeNames_get(const ArcadeNames* self, const char* filename);

#endif
