// Generated by tools/controller-art/make_pads.py; do not edit. The controller art of the Consoles tab:
// per console id, its brightness factor k (baked into the images), the Carousel image's aspect (w/h) and
// the List image's top-left on a 1024x768 and a 1280x720 screen. Included by controller_art_model.c only
// (PadTableRow is in controller_art_model.h).
#ifndef CONTROLLER_ART_TABLE_H
#define CONTROLLER_ART_TABLE_H

static const PadTableRow pad_table[] = {
	{"a2600", 2.00f, 0.9797f, 362, 0, 592, 0},
	{"a5200", 2.00f, 0.4203f, 579, 0, 797, 0},
	{"a7800", 1.12f, 0.4359f, 573, 0, 790, 0},
	{"c64", 1.00f, 0.9844f, 559, 0, 778, 0},
	{"coleco", 2.00f, 0.4594f, 557, 0, 776, 0},
	{"dc", 0.64f, 0.9656f, 428, 15, 654, 14},
	{"fc", 0.80f, 2.2069f, 407, 179, 508, 98},
	{"fds", 1.12f, 2.1477f, 412, 173, 515, 91},
	{"gb", 0.77f, 0.6062f, 508, 0, 729, 0},
	{"gba", 1.15f, 1.7112f, 426, 141, 534, 51},
	{"gbc", 1.26f, 0.6156f, 501, 0, 722, 0},
	{"gg", 2.00f, 1.7251f, 423, 143, 529, 53},
	{"lynx", 2.00f, 1.9512f, 425, 155, 532, 70},
	{"md", 1.80f, 1.9453f, 446, 191, 561, 116},
	{"n64", 0.79f, 1.0866f, 403, 25, 592, 0},
	{"nds", 0.65f, 1.0143f, 364, 0, 582, 0},
	{"ngpc", 0.89f, 1.6244f, 400, 115, 500, 20},
	{"pce", 0.75f, 1.9876f, 419, 185, 523, 109},
	{"pkm", 1.18f, 0.8156f, 425, 0, 652, 0},
	{"ps", 1.00f, 1.5459f, 442, 106, 554, 9},
	{"psp", 1.50f, 2.2535f, 431, 182, 540, 103},
	{"sfc", 0.71f, 2.1769f, 432, 178, 540, 99},
	{"sg1000", 1.06f, 0.4156f, 578, 0, 794, 0},
	{"sms", 2.00f, 2.2535f, 409, 182, 512, 102},
	{"vb", 2.00f, 1.1130f, 395, 14, 581, 0},
	{"vic20", 0.81f, 1.6452f, 432, 199, 540, 124},
	{"wsc", 2.00f, 1.6121f, 410, 116, 513, 20},
};

#endif
