#ifndef ARCADE_NAMES_H
#define ARCADE_NAMES_H

// Arcade display-name tables: .system/res/arcade/<TAG>.txt, generated by
// scripts/gen-arcade-names.sh from the FBNeo DATs (FBN) and Flycast's Naomi
// tables (DC). Each line is "<zip stem>\t<title>[\t<qualifier>]"; BIOS sets
// carry the title "." so hide() drops them, like a "."-prefixed map.txt alias.
// Titles are plain (no revision/region brackets, first of " / " names); the
// dropped bracket groups are kept as the qualifier, e.g. "(Japan 940520)",
// so clones sharing a title can still be told apart. The launcher
// (game lists) and minarch (in-game menu title) consult a table only when
// map.txt has no alias for the ROM.
//
// Depends on libc only, so the host unit tests can link it directly.

#include <stddef.h>

typedef struct ArcadeNames ArcadeNames;

// NULL when the file is missing, unreadable or has no entries.
ArcadeNames* ArcadeNames_load(const char* path);
void ArcadeNames_free(ArcadeNames* self);

// True for a .zip/.7z filename (any case) with a non-empty stem: the only files
// a table can name. Lets callers skip loading a table for everything else.
int ArcadeNames_isArcadeFile(const char* filename);

// The table (res/arcade/<tag>.txt) a folder tag reads: an alternate core's tag
// shares its system's table (Dreamcast Lite's DCX reads DC.txt).
const char* ArcadeNames_tableTag(const char* tag);

// Title for a ROM filename (e.g. "mslug.zip"), or NULL when the table does
// not know it. Only .zip and .7z files are looked up (any case), so disc
// images sharing a folder with arcade sets (DC's .chd/.gdi) keep their names.
const char* ArcadeNames_get(const ArcadeNames* self, const char* filename);

// The bracket groups the title dropped for a ROM filename (e.g.
// "(Japan 940520)"), or NULL when the table has none for it. Same lookup
// rules as ArcadeNames_get.
const char* ArcadeNames_getQualifier(const ArcadeNames* self, const char* filename);

// Labels for n rows that share one title, from their qualifiers: the
// bracketed region word ("(Japan)") when every qualified row has a distinct
// one, else the whole qualifier when those are all distinct. One row may have
// no (NULL or empty) qualifier, usually the parent set; its label is "" and it
// keeps the bare title. When the qualifiers cannot tell every row apart, each
// row is labelled by its filename without the extension ("(vtenis2c)"), or
// with it if two of those collide. Writes labels[i] (each label_size bytes)
// and returns 1, or returns 0 for fewer than two rows, a NULL filename or a
// label that would not fit; the caller then keeps its own labels.
int ArcadeNames_disambiguate(const char* const* qualifiers, const char* const* filenames, int n, char** labels, size_t label_size);

#endif
