#!/bin/sh
# Writes workspace/all/scraper/ss_credentials.h (git-ignored) from
# SS_DEV_ID / SS_DEV_PASSWORD, XOR-encoded so the plain strings don't show up
# in `strings scraper.elf`. Values come from the environment (the release
# workflow feeds them from GitHub secrets/variables) or, for local builds, from
# the untracked .env at the repo root (see .env.example). Without the header
# the scraper builds with empty ScreenScraper dev credentials (and a
# compile-time warning).
#
# --optional: exit quietly when no credentials are available (used by
# `make build`, so contributors without a .env still build).
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/workspace/all/scraper/ss_credentials.h"
OPTIONAL=0
[ "${1:-}" = "--optional" ] && OPTIONAL=1

# Read KEY=VALUE from .env without sourcing it; strips surrounding quotes.
env_value() {
	[ -f "$ROOT/.env" ] || return 0
	sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ROOT/.env" | tail -n 1 |
		sed -e 's/[[:space:]]*$//' -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/"
}

SS_DEV_ID="${SS_DEV_ID:-$(env_value SS_DEV_ID)}"
SS_DEV_PASSWORD="${SS_DEV_PASSWORD:-$(env_value SS_DEV_PASSWORD)}"

if [ -z "$SS_DEV_ID" ] || [ -z "$SS_DEV_PASSWORD" ]; then
	[ "$OPTIONAL" = 1 ] && exit 0
	echo "gen-ss-credentials: SS_DEV_ID and SS_DEV_PASSWORD must both be set (environment or .env)" >&2
	exit 1
fi

# Must match SS_XOR_KEY in scraper_api.c
encode() {
	printf '%s' "$1" | od -An -v -tu1 | tr -s ' \n' '\n\n' | sed '/^$/d' |
		while read -r b; do printf '0x%02x, ' $((b ^ 0x5A)); done
}

TMP="$OUT.tmp"
{
	echo "// Generated by scripts/gen-ss-credentials.sh -- do not commit."
	echo "static const unsigned char ss_devid_enc[] = {$(encode "$SS_DEV_ID")};"
	echo "static const unsigned char ss_devpass_enc[] = {$(encode "$SS_DEV_PASSWORD")};"
} >"$TMP"

# Leave the header (and its mtime) alone when nothing changed
if cmp -s "$TMP" "$OUT"; then
	rm -f "$TMP"
else
	mv "$TMP" "$OUT"
	echo "gen-ss-credentials: wrote $OUT"
fi
