#!/bin/bash
set -ex

# ============================================================
# SDL2 build for tg5040 NDS (drastic) with compiled-in hooks
#
# Same hook patches as tg5050 but WITHOUT DRM/GBM:
# - tg5040 renders via /dev/fb0 + PowerVR EGL (not DRM)
# - No -DADVDRASTIC_DRM flag
# - Dummy driver reads resolution from framebuffer ioctl
# - eglSwapInterval(1) for fbdev vsync (no DRM page flips)
# ============================================================

# ============================================================
# Step 1: Set up toolchain environment
# ============================================================
source ~/.bashrc

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EXTRA_PREFIX="$(pwd)/extra-deps"

# ============================================================
# Step 2: Install extra-deps headers (json-c only)
# tg5040 uses fbdev/PowerVR — no DRM/GBM headers needed.
# EGL/GLES headers are already in the sysroot.
# ============================================================
if [ ! -f "$EXTRA_PREFIX/.deps_installed" ]; then
    mkdir -p "$EXTRA_PREFIX/include" "$EXTRA_PREFIX/lib"

    # json-c headers (needed by hook code's jsonlayout.c)
    git clone --depth 1 --branch json-c-0.15 https://github.com/json-c/json-c.git /tmp/json-c
    mkdir -p "$EXTRA_PREFIX/include/json-c"
    cp /tmp/json-c/*.h "$EXTRA_PREFIX/include/json-c/"
    rm -rf /tmp/json-c

    # json_config.h stub (normally generated by cmake)
    cat > "$EXTRA_PREFIX/include/json-c/json_config.h" << 'CONFEOF'
#ifndef _json_config_h_
#define _json_config_h_
#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDINT_H 1
#endif
CONFEOF

    # SDL2_ttf and SDL2_image headers (needed by hook code in drastic_video.h)
    cp ${SYSROOT}/usr/include/SDL2/SDL_ttf.h "$EXTRA_PREFIX/include/"
    cp ${SYSROOT}/usr/include/SDL2/SDL_image.h "$EXTRA_PREFIX/include/"

    # json-c stub library (symbols resolved on device)
    cat > /tmp/json_stub.c << 'STUBEOF'
void json_object_new_int(void){} void json_object_put(void){} void json_object_to_file_ext(void){}
void json_object_from_file(void){} void json_object_object_add(void){} void json_object_get_string(void){}
void json_object_get_int(void){} void json_object_object_get_ex(void){} void json_object_new_string(void){}
void json_object_new_object(void){} void json_object_new_array(void){} void json_object_array_add(void){}
void json_object_array_length(void){} void json_object_array_get_idx(void){}
void json_object_object_get(void){} void json_object_get_type(void){}
STUBEOF
    ${CC} -shared -Wl,-soname,libjson-c.so.4 -o "$EXTRA_PREFIX/lib/libjson-c.so" /tmp/json_stub.c

    touch "$EXTRA_PREFIX/.deps_installed"
    echo "=== Extra deps installed ==="
fi

# ============================================================
# Step 3: SDL_drastic source must be pre-cloned and patched
# Run 'make other/sdl2-drastic/SDL_drastic' from workspace/tg5040
# ============================================================
if [ ! -d SDL_drastic ]; then
    echo "ERROR: SDL_drastic source not found. Run from workspace/tg5040:"
    echo "  make other/sdl2-drastic/SDL_drastic"
    exit 1
fi

cd SDL_drastic

# ============================================================
# Step 4: Generate configure
# ============================================================
if [ ! -f configure ]; then
    ./autogen.sh
fi

# Clean previous build (force rebuild when CFLAGS change)
[ -f Makefile ] && make clean || true

# ============================================================
# Step 7: Configure — dummy driver + OpenGL ES (no KMSDRM)
# Note: Do NOT include sysroot SDL2 headers (version mismatch).
# The hook code's SDL2 includes resolve from the source tree.
# No -DADVDRASTIC_DRM: tg5040 uses /dev/fb0, not DRM.
# ============================================================
export PKG_CONFIG_PATH="${SYSROOT}/usr/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR=""

./configure \
    --host=${CROSS_TRIPLE} \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --disable-rpath \
    --disable-arts \
    --disable-esd \
    --disable-dbus \
    --disable-pulseaudio \
    --disable-video-vivante \
    --disable-video-cocoa \
    --disable-video-metal \
    --enable-video-dummy \
    --disable-video-offscreen \
    --disable-video-x11 \
    --disable-video-wayland \
    --disable-video-kmsdrm \
    --disable-ime \
    --disable-ibus \
    --disable-fcitx \
    --disable-joystick-mfi \
    --disable-directx \
    --disable-xinput \
    --disable-wasapi \
    --disable-hidapi-joystick \
    --disable-hidapi-libusb \
    --disable-joystick-virtual \
    --disable-render-d3d \
    --disable-hidapi \
    --enable-video-opengles \
    --enable-video-opengles1 \
    --enable-video-opengles2 \
    --enable-alsa \
    --disable-libudev \
    CFLAGS="-O2 -Wno-error -DDEVICE_TRIMUI -I${EXTRA_PREFIX}/include" \
    CPPFLAGS="-I${EXTRA_PREFIX}/include" \
    LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib"

# Suppress -Werror flags (hook code has many harmless warnings)
sed -i 's/-Werror=declaration-after-statement/-Wno-error/g' Makefile

# ============================================================
# Step 8: Build — add hook link deps via EXTRA_LDFLAGS
# No -ldrm/-lgbm: tg5040 uses fbdev, not DRM/GBM.
# ============================================================
make -j$(nproc) \
    EXTRA_LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib -lSDL2_image -lSDL2_ttf -ljson-c -lpthread -lEGL -lGLESv2 -lm -ldl"

# ============================================================
# Step 9: Output
# ============================================================
mkdir -p "$SCRIPT_DIR/output"
cp build/.libs/libSDL2-2.0.so.0 "$SCRIPT_DIR/output/"
echo "=== Build complete ==="
ls -la "$SCRIPT_DIR/output/libSDL2-2.0.so.0"
file "$SCRIPT_DIR/output/libSDL2-2.0.so.0"
strings "$SCRIPT_DIR/output/libSDL2-2.0.so.0" | grep -i "FB display\|dummy\|DraStic"
