---
name: Release NextUI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "release type"
        default: "patch"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      next-tag: ${{ steps.next-tag.outputs.version }}
      release-name: ${{ steps.release-name.outputs.RELEASE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate Release Name
        id: release-name
        run: |
          echo "RELEASE_NAME=$(make name)" >> "$GITHUB_OUTPUT"

      - name: Get Latest Tag
        id: latest-tag
        run: |
          echo GIT_LATEST_TAG="$(git describe --tags "$(git rev-list --tags --max-count=1)")" >>"$GITHUB_OUTPUT"

      - name: Compute Next Tag
        id: next-tag
        uses: docker://ghcr.io/dokku/semver-generator:latest
        with:
          bump: ${{ github.event.inputs.release_type }}
          input: ${{ steps.latest-tag.outputs.GIT_LATEST_TAG }}

  build:
    needs: prepare
    runs-on: ubuntu-24.04-arm
    env:
      RELEASE_NAME: ${{ needs.prepare.outputs.release-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zipmerge

      - name: Build
        run: make all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: release-artifacts
          path: releases/${{ env.RELEASE_NAME }}-*.zip

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.3.0
        with:
          subject-path: releases/${{ env.RELEASE_NAME }}-*.zip

  release:
    needs:
      - build
      - prepare
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: releases/
          pattern: release-artifacts
          merge-multiple: true

      - name: Create and Push Tag
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag "$GIT_NEXT_TAG"
          git push origin "$GIT_NEXT_TAG"
        env:
          GIT_NEXT_TAG: ${{ needs.prepare.outputs.next-tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/*
          generate_release_notes: true
          append_body: true
          tag_name: ${{ needs.prepare.outputs.next-tag }}
          make_latest: "true"
          body: |

            For full features list and help on how to use etc of NextUI:
            https://nextui.loveretro.games/docs/

            ## How to install/update
            For a fresh installation, follow the instructions here: https://nextui.loveretro.games/getting-started/installation/
            When updating from a previous release: https://nextui.loveretro.games/getting-started/updating/
